#!/usr/bin/env python3
"""
evaluate_hybrid_v2.py — Corrected evaluation of the Drift hybrid recommender.

Fixes applied vs v1:
  1. Sampled-negative protocol: 1 held-out positive + 99 random negatives →
     HR@1, HR@10, NDCG@10 on the 100-item pool (not full-catalog Precision@1).
  2. Fixed template-sentence mood queries: 27 pre-embedded template sentences
     (one per capacity×tone×context triple) replace the self-referential
     target-movie-embedding + noise that leaked the answer into the query.

Run from: drift/backend/
Requires:
  src/data/cf_candidates.json
  src/data/movie_features.json
  src/data/template_embeddings.json   ← generated by generate_template_embeddings.ts
  ml-32m/ratings.csv                  ← for user history and popularity
"""

import json
import math
import os
import sys
import numpy as np
import pandas as pd
from tqdm import tqdm

# ─── Genre constants (must match generate_embeddings.ts and train_cf.py) ──────

ALL_GENRES = [
    'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
    'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical',
    'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western',
]
GENRE_TO_IDX = {g: i for i, g in enumerate(ALL_GENRES)}

# ─── Feature helpers ───────────────────────────────────────────────────────────

def genre_one_hot(genres):
    v = np.zeros(len(ALL_GENRES), dtype=np.float32)
    for g in genres:
        if g in GENRE_TO_IDX:
            v[GENRE_TO_IDX[g]] = 1.0
    return v

def build_movie_vector(feats):
    """403-dim: [genre_one_hot(18), runtime_norm(1)*0.2, sentence_embedding(384)]"""
    gh = genre_one_hot(feats.get('genres', []))
    rt = min(feats.get('runtime', 90), 200) / 200.0
    emb = np.array(feats['embedding'], dtype=np.float32)
    return np.concatenate([gh, [rt * 0.2], emb])

def build_query_vector(capacity, tone, context, template_emb):
    """
    Build the 403-dim mood query vector.
    Text component = pre-embedded template sentence (NOT the target movie's embedding).
    """
    # Genre query weights from tone
    gq = np.zeros(len(ALL_GENRES), dtype=np.float32)
    if tone == 'comfort':
        for g in ['Comedy', 'Children', 'Animation']:
            gq[GENRE_TO_IDX[g]] += 1.0
        for g in ['Romance', 'Musical']:
            gq[GENRE_TO_IDX[g]] += 0.8
    elif tone == 'stimulation':
        for g in ['Action', 'Thriller']:
            gq[GENRE_TO_IDX[g]] += 1.0
        for g in ['Crime', 'Horror', 'Sci-Fi']:
            gq[GENRE_TO_IDX[g]] += 0.8
    elif tone == 'escapism':
        for g in ['Adventure', 'Fantasy', 'Sci-Fi']:
            gq[GENRE_TO_IDX[g]] += 1.0
        for g in ['Animation', 'Western']:
            gq[GENRE_TO_IDX[g]] += 0.6

    # Context boosts
    if context == 'background':
        for g in ['Comedy', 'Children']:
            gq[GENRE_TO_IDX[g]] += 0.5
    elif context == 'focused':
        for g in ['Drama', 'Mystery', 'Crime']:
            gq[GENRE_TO_IDX[g]] += 1.0
    elif context == 'alone':
        for g in ['Drama', 'Romance']:
            gq[GENRE_TO_IDX[g]] += 0.5

    norm = np.linalg.norm(gq)
    if norm > 0:
        gq /= norm

    # Runtime preference from capacity
    rt_pref = {'low': 0.2, 'medium': 0.5, 'high': 0.9}.get(capacity, 0.5)

    # Template sentence embedding — completely independent of the target movie
    emb = np.array(template_emb, dtype=np.float32)

    return np.concatenate([gq, [rt_pref * 0.2], emb])

def cosine(a, b):
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    if na == 0.0 or nb == 0.0:
        return 0.0
    return float(np.dot(a, b) / (na * nb))

# ─── Synthetic mood generation (same rule-based logic as v1, 15% noise) ────────

def synthetic_mood(genres, runtime):
    genres_set = set(genres)

    # Capacity from runtime
    if runtime < 100:
        cap = np.random.choice(['low', 'medium'], p=[0.6, 0.4])
    elif runtime > 120:
        cap = np.random.choice(['high', 'medium'], p=[0.7, 0.3])
    else:
        cap = np.random.choice(['low', 'medium', 'high'], p=[0.2, 0.6, 0.2])

    # Tone from genres
    if genres_set & {'Comedy', 'Children', 'Animation', 'Romance', 'Musical'}:
        tone = 'comfort'
    elif genres_set & {'Action', 'Thriller', 'Horror', 'Crime'}:
        tone = 'stimulation'
    elif genres_set & {'Sci-Fi', 'Fantasy', 'Adventure'}:
        tone = 'escapism'
    else:
        tone = 'comfort'

    # Context from genres
    if genres_set & {'Comedy', 'Children', 'Animation'}:
        ctx = 'background'
    elif genres_set & {'Drama', 'Mystery', 'Crime'}:
        ctx = 'focused'
    else:
        ctx = 'alone'

    # 15% independent random noise on each field
    if np.random.rand() < 0.15:
        cap = np.random.choice(['low', 'medium', 'high'])
    if np.random.rand() < 0.15:
        tone = np.random.choice(['comfort', 'stimulation', 'escapism'])
    if np.random.rand() < 0.15:
        ctx = np.random.choice(['alone', 'background', 'focused'])

    return cap, tone, ctx

# ─── Evaluation metrics ───────────────────────────────────────────────────────

def ndcg_at_k(rank_1indexed, k=10):
    """NDCG@k for binary relevance with one relevant item."""
    if rank_1indexed <= k:
        return 1.0 / math.log2(rank_1indexed + 1)
    return 0.0

def run_evaluation(test_queries, scoring_fn, label):
    """
    Score each user's 100-item pool, rank, compute HR@1/HR@10/NDCG@10.
    scoring_fn(q, items_100) → dict {movieId: float}

    Ties are broken uniformly at random to prevent list-insertion-order bias.
    (Python sorted() is stable, so without shuffling the positive item at
    index 0 would always win ties — inflating all metrics.)
    """
    hr1 = hr10 = 0
    ndcg10_total = 0.0
    n = 0

    for q in tqdm(test_queries, desc=f'  {label:<30}', leave=False):
        items = list(q['items_100'])     # copy so we can shuffle
        pos   = q['pos_mid']

        scores = scoring_fn(q, items)    # {movieId: score}

        # Shuffle first to randomise tie-breaking order
        np.random.shuffle(items)
        # Then sort descending by score (stable on shuffled list → random ties)
        ranked = sorted(items, key=lambda m: scores.get(m, 0.0), reverse=True)
        rank   = ranked.index(pos) + 1  # 1-indexed

        hr1        += int(rank == 1)
        hr10       += int(rank <= 10)
        ndcg10_total += ndcg_at_k(rank, 10)
        n          += 1

    return {
        'HR@1':    hr1 / n if n else 0.0,
        'HR@10':   hr10 / n if n else 0.0,
        'NDCG@10': ndcg10_total / n if n else 0.0,
        'N':       n,
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print('=' * 62)
    print('  Drift Hybrid Recommender — Corrected Evaluation (v2)')
    print('=' * 62)

    # ── Load artefacts ────────────────────────────────────────────────────────
    paths = {
        'cf':        'src/data/cf_candidates.json',
        'features':  'src/data/movie_features.json',
        'templates': 'src/data/template_embeddings.json',
    }
    for name, p in paths.items():
        if not os.path.exists(p):
            print(f'ERROR: {p} not found. Cannot continue.')
            sys.exit(1)

    print('\nLoading data files...')
    with open(paths['cf'])        as f: cf_data    = json.load(f)
    with open(paths['features'])  as f: mf         = json.load(f)
    with open(paths['templates']) as f: templates  = json.load(f)

    test_set   = cf_data['test_set']         # [{userId, movieId}, ...]
    candidates = cf_data['candidates']       # {uid_str: [{movieId, score}]}
    stats      = cf_data['stats']
    user_to_idx = cf_data.get('user_to_idx', {})
    movie_to_idx = cf_data.get('movie_to_idx', {})
    idx_to_movie = {v: int(k) for k, v in movie_to_idx.items()}

    # Load ALS factors if available (enables full-catalog dot-product scoring)
    factors_path_u = 'src/data/user_factors.npy'
    factors_path_i = 'src/data/item_factors.npy'
    user_factors = None
    item_factors = None
    if os.path.exists(factors_path_u) and os.path.exists(factors_path_i):
        user_factors = np.load(factors_path_u)
        item_factors = np.load(factors_path_i)
        print(f'  ALS factors loaded: user_factors {user_factors.shape}, item_factors {item_factors.shape}')
    else:
        print('  WARNING: ALS factors not found — falling back to truncated candidate lists.')

    print(f'  cf_candidates  : {len(test_set)} test users, '
          f'{len(candidates)} candidate lists')
    print(f'  movie_features : {len(mf)} movies')
    print(f'  templates      : {len(templates)} embeddings')

    # ── Build movie vectors ───────────────────────────────────────────────────
    print('\nBuilding 403-dim movie feature vectors...')
    movie_vectors = {int(mid): build_movie_vector(feats) for mid, feats in mf.items()}
    available_mids = set(movie_vectors.keys())
    print(f'  {len(available_mids)} movies with vectors')

    # ── Load ratings.csv for user history + global popularity ─────────────────
    ratings_path = 'ml-32m/ratings.csv'
    if not os.path.exists(ratings_path):
        print(f'\nWARNING: {ratings_path} not found.')
        print('  Falling back: user history = top-50 candidates; popularity = 1 for all.')
        user_history = {
            e['userId']: {c['movieId'] for c in candidates.get(str(e['userId']), [])}
            for e in test_set
        }
        popularity = {}
    else:
        print('\nLoading ratings.csv (userId + movieId columns only)...')
        rdf = pd.read_csv(
            ratings_path,
            usecols=['userId', 'movieId'],
            dtype={'userId': np.int32, 'movieId': np.int32},
        )
        popularity = rdf['movieId'].value_counts().to_dict()

        test_uids = {int(e['userId']) for e in test_set}
        user_history = (
            rdf[rdf['userId'].isin(test_uids)]
            .groupby('userId')['movieId']
            .apply(set)
            .to_dict()
        )
        del rdf
        print(f'  Popularity counts: {len(popularity):,} movies')
        print(f'  User histories  : {len(user_history)} test users')

    # ── Generate test queries ─────────────────────────────────────────────────
    print('\nGenerating synthetic mood queries (template embeddings)...')
    np.random.seed(42)

    test_queries = []
    skipped = 0

    for entry in test_set:
        uid     = int(entry['userId'])
        pos_mid = int(entry['movieId'])

        # Need feature vector for positive item
        if pos_mid not in movie_vectors:
            skipped += 1
            continue

        pos_feats = mf[str(pos_mid)]
        cap, tone, ctx = synthetic_mood(
            pos_feats.get('genres', []),
            pos_feats.get('runtime', 90),
        )

        # Template embedding — independent of the target movie
        key = f'{cap}_{tone}_{ctx}'
        templ_emb = templates.get(key)
        if templ_emb is None:
            skipped += 1
            continue

        query_vec = build_query_vector(cap, tone, ctx, templ_emb)

        # Sample 99 negatives from available movies not in user's rating history
        rated = user_history.get(uid, set())
        pool  = list(available_mids - rated - {pos_mid})

        if len(pool) < 99:
            skipped += 1
            continue

        neg_99 = np.random.choice(pool, size=99, replace=False).tolist()

        test_queries.append({
            'userId':   uid,
            'pos_mid':  pos_mid,
            'capacity': cap,
            'tone':     tone,
            'context':  ctx,
            'query_vec': query_vec,
            'items_100': [pos_mid] + neg_99,  # pos always index 0 for tracking
        })

    print(f'  Valid queries : {len(test_queries)}')
    print(f'  Skipped       : {skipped}')

    # ── Scoring functions ─────────────────────────────────────────────────────

    def score_popularity(q, items):
        return {m: float(popularity.get(m, 0)) for m in items}

    def score_cf(q, items):
        """Score using full ALS dot-product if factors available, else truncated candidates."""
        if user_factors is not None:
            uid = q['userId']
            u_idx = user_to_idx.get(str(uid))
            if u_idx is not None and u_idx < len(user_factors):
                u_vec = user_factors[u_idx]  # shape: (factors,)
                scores = {}
                for m in items:
                    m_idx = movie_to_idx.get(str(m))
                    if m_idx is not None and m_idx < len(item_factors):
                        scores[m] = float(np.dot(u_vec, item_factors[m_idx]))
                    else:
                        scores[m] = 0.0
                return scores
        # Fallback: truncated candidate list
        score_map = {c['movieId']: c['score']
                     for c in candidates.get(str(q['userId']), [])}
        return {m: score_map.get(m, 0.0) for m in items}

    def score_hybrid(q, items, alpha):
        cf_scores_raw = score_cf(q, items)

        # Normalise CF scores over the 100-item pool
        all_cf = list(cf_scores_raw.values())
        min_cf = min(all_cf) if all_cf else 0.0
        max_cf = max(all_cf) if all_cf else 1.0
        cf_range = max_cf - min_cf if max_cf > min_cf else 1.0

        qv = q['query_vec']
        result = {}
        for m in items:
            cf_norm = max(0.0, (cf_scores_raw.get(m, 0.0) - min_cf) / cf_range)

            # Mood similarity via cosine
            mv = movie_vectors.get(m)
            mood_sim = cosine(qv, mv) if mv is not None else 0.0

            result[m] = alpha * cf_norm + (1.0 - alpha) * mood_sim
        return result

    # ── Evaluate three models ─────────────────────────────────────────────────
    print(f'\n{"=" * 62}')
    print('  Evaluating models on 100-item sampled-negative pools...')
    print(f'{"=" * 62}')

    pop_res = run_evaluation(test_queries, score_popularity, 'Popularity Baseline')
    cf_res  = run_evaluation(test_queries, score_cf,        'CF-Only (ALS)')

    # Alpha sweep
    print()
    alphas        = [0.3, 0.4, 0.5, 0.6, 0.7]
    alpha_results = {}
    best_alpha    = 0.5
    best_ndcg     = -1.0

    for a in alphas:
        res = run_evaluation(
            test_queries,
            lambda q, items, _a=a: score_hybrid(q, items, _a),
            f'Hybrid α={a:.1f}',
        )
        alpha_results[a] = res
        if res['NDCG@10'] > best_ndcg:
            best_ndcg  = res['NDCG@10']
            best_alpha = a

    best_res = alpha_results[best_alpha]

    # ── Print results ─────────────────────────────────────────────────────────
    print(f'\n{"=" * 62}')
    print('  RESULTS  (N={} users, 100-item pool)'.format(len(test_queries)))
    print(f'{"=" * 62}')
    print(f'  {"Model":<32} {"HR@1":>6}  {"HR@10":>6}  {"NDCG@10":>9}')
    print(f'  {"-"*60}')
    print(f'  {"Random baseline (theoretical)":<32} {"1.00%":>6}  {"10.00%":>6}  {"0.0454":>9}')
    print(f'  {"Popularity Baseline":<32} {pop_res["HR@1"]*100:>5.2f}%  {pop_res["HR@10"]*100:>5.2f}%  {pop_res["NDCG@10"]:>9.4f}')
    print(f'  {"CF-Only (ALS Stage 1)":<32} {cf_res["HR@1"]*100:>5.2f}%  {cf_res["HR@10"]*100:>5.2f}%  {cf_res["NDCG@10"]:>9.4f}')
    print(f'  {"-"*60}')
    print(f'  {"Alpha sweep:":<32}')
    for a, r in alpha_results.items():
        marker = ' ← best' if a == best_alpha else ''
        print(f'    α={a:.1f}: HR@1={r["HR@1"]*100:.2f}%  HR@10={r["HR@10"]*100:.2f}%  NDCG@10={r["NDCG@10"]:.4f}{marker}')
    print(f'  {"-"*60}')
    print(f'  {"Full Hybrid (α="+str(best_alpha)+")":<32} {best_res["HR@1"]*100:>5.2f}%  {best_res["HR@10"]*100:>5.2f}%  {best_res["NDCG@10"]:>9.4f}')
    print(f'{"=" * 62}\n')

    # ── Build lean deployment assets (recommender_assets.json) ────────────────
    print('\nBuilding deployment assets (recommender_assets.json)...')

    popularity_fallback = cf_data.get('popularity_fallback', [])

    # Prune movie_features to only movies referenced in candidates + popularity fallback
    referenced_mids = set()
    for cand_list in candidates.values():
        for c in cand_list:
            referenced_mids.add(str(c['movieId']))
    for c in popularity_fallback:
        referenced_mids.add(str(c['movieId']))

    pruned_mf = {mid: feats for mid, feats in mf.items() if mid in referenced_mids}
    print(f'  Pruned movie features: {len(mf)} → {len(pruned_mf)} referenced shows')

    deployment_assets = {
        'alpha': best_alpha,
        'genres': ALL_GENRES,
        'movie_features': pruned_mf,
        'candidates': candidates,
        'popularity_fallback': popularity_fallback,
        'user_to_idx': user_to_idx,
        'movie_to_idx': movie_to_idx,
    }

    # Embed factor arrays as lists if available (for serve-time dot product)
    if user_factors is not None:
        deployment_assets['user_factors_path'] = 'src/data/user_factors.npy'
        deployment_assets['item_factors_path'] = 'src/data/item_factors.npy'

    assets_path = 'src/data/recommender_assets.json'
    print(f'  Writing {assets_path}...')
    with open(assets_path, 'w') as f:
        json.dump(deployment_assets, f)
    print(f'  Saved: alpha={best_alpha}, {len(mf)} shows, {len(user_to_idx)} users')

    # ── Write updated report ──────────────────────────────────────────────────
    _write_report(
        stats, test_queries, available_mids,
        pop_res, cf_res, alpha_results, best_alpha, best_res,
    )
    print('\n=== Evaluation v2 complete ===')


# ─── Report writer ────────────────────────────────────────────────────────────

def _write_report(stats, test_queries, available_mids,
                  pop_res, cf_res, alpha_results, best_alpha, best_res):
    N = len(test_queries)

    alpha_table = '\n'.join(
        f'| {a:.1f} | {r["HR@1"]*100:.2f}% | {r["HR@10"]*100:.2f}% '
        f'| {r["NDCG@10"]:.4f} |{"  ← selected" if a == best_alpha else ""}'
        for a, r in alpha_results.items()
    )

    report = f"""# Drift Recommender System — Evaluation Report (v2)

> This report supersedes v1. Two methodological corrections have been applied:
> (1) full-catalog Precision@1 replaced with the sampled-negative Hit Rate /
> NDCG protocol, and (2) self-referential mood query embedding replaced with
> fixed template sentences.

---

## 1. Why the Evaluation Protocol Changed

### Original approach (v1) — full-catalog Precision@1

For each of the 300 test users, the held-out item was ranked against all
**23,172 movies** in the training catalog. Precision@1 asked: "Is it ranked
first out of 23,172?" This is an extremely hard task:

- A random model achieves P@1 ≈ 1/23,172 ≈ **0.004%**
- Even a well-trained ALS model rarely puts a single specific item first out
  of 23,172 possibilities
- The metric is dominated by catalog size, making it uninformative for
  comparing models against each other

### Corrected approach (v2) — sampled-negative protocol

The **standard protocol** used in virtually all modern recommender-systems
research (He et al. 2017 — NCF; Kang & McAuley 2018 — SASRec; Sun et al.
2019 — BERT4Rec; Rendle et al. 2009 — BPR):

For each test user:
1. Take the one held-out positive item.
2. **Sample 99 items the user never rated** as negatives.
3. Score all 100 items with the model and rank them.
4. Measure whether the positive item is ranked highly.

Metrics on the 100-item ranked list:
- **HR@1** — Hit Rate at 1: did the model rank the positive item first?
- **HR@10** — Hit Rate at 10: is the positive in the top 10?
- **NDCG@10** — Normalised Discounted Cumulative Gain at 10: rewards higher
  ranks within the top 10 (1/log₂(rank+1), normalised by ideal DCG).

This protocol is fair, discriminative, and directly comparable to published
benchmarks. The random baseline is exactly:
HR@1 = 1%, HR@10 = 10%, NDCG@10 ≈ 0.0454.

### Self-referential query fix

v1 constructed the mood query's text embedding as: `target_movie_embedding +
Gaussian_noise(σ=0.08)`. This leaked the answer: the query was semantically
similar to the target by construction, inflating the hybrid model's score.

v2 uses **27 fixed template sentences** — one per (capacity × tone × context)
triple — embedded with the same `all-MiniLM-L6-v2` model used for movies, but
**completely independently** of any target movie. The (capacity, tone, context)
label is still derived from the target movie's genre/runtime (as a proxy for a
real user's stated preference), but the 384-dim embedding component of the
query is now free of target-item information.

---

## 2. Dataset Statistics

| | Before Filtering | After ≥ 20 Ratings Filter + 25k Sample |
|:---|---:|---:|
| Ratings | {stats['initial_ratings']:,} | {stats['filtered_ratings']:,} |
| Users | {stats['initial_users']:,} | {stats['filtered_users']:,} |
| Movies | {stats['initial_movies']:,} | {stats['filtered_movies']:,} |

- ALS trained on a **25,000-user random sample** (memory constraint on 16 GB RAM).
- Leave-one-out split: each user's most recent rating by timestamp held out.
- Evaluation sample: **{N} users** with valid feature vectors and sufficient negative pool.
- Negative sampling pool: {len(available_mids):,} movies with pre-computed sentence
  embeddings, excluding each user's full rating history.

---

## 3. Sampled-Negative Evaluation Results

Each user's held-out item ranked against 99 randomly sampled unrated items:

| Model | HR@1 | HR@10 | NDCG@10 |
|:---|:---:|:---:|:---:|
| Random baseline (theoretical) | 1.00% | 10.00% | 0.0454 |
| **Popularity Baseline** | {pop_res['HR@1']*100:.2f}% | {pop_res['HR@10']*100:.2f}% | {pop_res['NDCG@10']:.4f} |
| **CF-Only (ALS, Stage 1)** | {cf_res['HR@1']*100:.2f}% | {cf_res['HR@10']*100:.2f}% | {cf_res['NDCG@10']:.4f} |
| **Full Hybrid (α = {best_alpha:.1f}, Stage 1+2)** | {best_res['HR@1']*100:.2f}% | {best_res['HR@10']*100:.2f}% | {best_res['NDCG@10']:.4f} |

---

## 4. Alpha Sweep Results

$$\\text{{final\\_score}} = \\alpha \\cdot \\text{{CF\\_norm}} + (1 - \\alpha) \\cdot \\text{{cosine\\_mood\\_sim}}$$

| α | HR@1 | HR@10 | NDCG@10 | |
|:---:|:---:|:---:|:---:|:---|
{alpha_table}

Best α = **{best_alpha:.1f}** (selected by NDCG@10 = {best_res['NDCG@10']:.4f}).

---

## 5. Synthetic Mood Data Generation

The (capacity, tone, context) label for each test instance is derived from the
**target movie's attributes** as a proxy for a real user's stated preferences
(since no real mood session data exists):

| Dimension | Rule | Values |
|:---|:---|:---|
| **Capacity** | TMDB runtime: < 100 min → low, > 120 min → high | low / medium / high |
| **Tone** | Genres: Comedy/Animation → comfort; Action/Thriller → stimulation; Sci-Fi/Fantasy → escapism | comfort / stimulation / escapism |
| **Context** | Genres: Comedy/Children → background; Drama/Crime → focused; else → alone | alone / background / focused |
| **Noise** | 15% random field mutation (independent) | — |

The **text embedding component** of the query is now a fixed template sentence
(e.g. *"a heartwarming drama to enjoy by myself"* for medium+comfort+alone),
not the target movie's embedding. This eliminates embedding-level leakage while
retaining realistic genre/runtime signal in the genre and runtime query dimensions.

**Important caveat:** mood labels are synthetic. The evaluation measures whether
the model's mood-content mapping is internally consistent with the rule-based
generator, not whether it satisfies real users' stated preferences. A deployment
evaluation would require a user study or live A/B test.

---

## 6. Architecture Summary (as implemented)

**Stage 1 — ALS Collaborative Filtering**
- Library: `implicit.AlternatingLeastSquares`
- Hyperparameters: factors=64, regularization=0.1, iterations=15
- Input: 25,000 × 23,172 sparse CSR matrix (ratings as implicit confidence)
- Output: top-50 scored candidates per user

**Stage 2 — Content/Mood Re-ranking**
- 403-dim feature vectors: [genre one-hot (18), runtime norm (1), sentence
  embedding (384)] via `all-MiniLM-L6-v2`
- Query vector built from (capacity, tone, context) with template sentence text
- Re-ranking formula: α·CF_norm + (1−α)·cosine_mood_sim
- Optimal α = **{best_alpha:.1f}** (by NDCG@10 on corrected evaluation)

---

## 7. Known Limitations

| Limitation | Impact |
|:---|:---|
| Synthetic mood labels | Evaluation measures rule-based label consistency, not real user preferences. |
| 25,000-user ALS subsample | ~12% of eligible users; full-scale ALS would have richer latent factors. |
| 300-user candidate coverage | Users outside the 300 evaluated fall back to popularity ranking at serve time. |
| Negative pool from feature set | Negatives drawn from 5,869-movie feature set (not all 23,172), making the evaluation slightly easier than true random negatives from the full catalog. |
| Genre-level query leakage | The capacity/tone/context labels are derived from target movie attributes, creating indirect genre correlation in the genre query weights (not eliminable without real user mood data). |
| MovieLens population bias | Dataset skews toward active English-speaking film enthusiasts. |
| No episode-level granularity | TV episode recommendations use a separate TMDB live endpoint, not the hybrid pipeline. |
| Offline evaluation only | No A/B test or live user feedback; actual user satisfaction may differ from offline metrics. |
"""

    with open('recommender_report.md', 'w') as f:
        f.write(report)
    print('Saved updated report → recommender_report.md')


if __name__ == '__main__':
    main()
